const typeAndServicesSeedData = [
  {
    businessType: "Hair Salon",
    services: [
      { serviceName: "Haircut" },
      { serviceName: "Hair Coloring" },
      { serviceName: "Blowout" },
      { serviceName: "Hair Extensions" },
      { serviceName: "Hair Treatment" },
      { serviceName: "Updo Styling" },
      { serviceName: "Keratin Treatment" },
      { serviceName: "Perm" },
      { serviceName: "Scalp Treatment" },
      { serviceName: "Hair Braiding" },
    ],
  },
  {
    businessType: "Barbershop",
    services: [
      { serviceName: "Haircut" },
      { serviceName: "Beard Trim" },
      { serviceName: "Hot Towel Shave" },
      { serviceName: "Hair Coloring" },
      { serviceName: "Head Shave" },
      { serviceName: "Line Up" },
      { serviceName: "Buzz Cut" },
      { serviceName: "Facial" },
      { serviceName: "Scalp Massage" },
      { serviceName: "Eyebrow Shaping" },
    ],
  },
  {
    businessType: "Nail Salon",
    services: [
      { serviceName: "Manicure" },
      { serviceName: "Pedicure" },
      { serviceName: "Gel Nails" },
      { serviceName: "Acrylic Nails" },
      { serviceName: "Nail Art" },
      { serviceName: "Nail Repair" },
      { serviceName: "French Manicure" },
      { serviceName: "Paraffin Treatment" },
      { serviceName: "Shellac Nails" },
      { serviceName: "Nail Extensions" },
    ],
  },
  {
    businessType: "Skin Care",
    services: [
      { serviceName: "Facial" },
      { serviceName: "Microdermabrasion" },
      { serviceName: "Chemical Peel" },
      { serviceName: "Acne Treatment" },
      { serviceName: "Anti-Aging Treatment" },
      { serviceName: "Hydrating Treatment" },
      { serviceName: "LED Light Therapy" },
      { serviceName: "Microneedling" },
      { serviceName: "Dermaplaning" },
      { serviceName: "Skin Tightening" },
    ],
  },
  {
    businessType: "Massage",
    services: [
      { serviceName: "Swedish Massage" },
      { serviceName: "Deep Tissue Massage" },
      { serviceName: "Hot Stone Massage" },
      { serviceName: "Sports Massage" },
      { serviceName: "Aromatherapy Massage" },
      { serviceName: "Prenatal Massage" },
      { serviceName: "Reflexology" },
      { serviceName: "Shiatsu Massage" },
      { serviceName: "Thai Massage" },
      { serviceName: "Trigger Point Therapy" },
    ],
  },
  {
    businessType: "Spa",
    services: [
      { serviceName: "Facial" },
      { serviceName: "Body Scrub" },
      { serviceName: "Massage" },
      { serviceName: "Mud Wrap" },
      { serviceName: "Steam Room" },
      { serviceName: "Manicure" },
      { serviceName: "Pedicure" },
      { serviceName: "Hydrotherapy" },
      { serviceName: "Aromatherapy" },
      { serviceName: "Sauna" },
    ],
  },
  {
    businessType: "Tattoo Shop",
    services: [
      { serviceName: "Custom Tattoo" },
      { serviceName: "Cover-up Tattoo" },
      { serviceName: "Tattoo Removal" },
      { serviceName: "Tattoo Consultation" },
      { serviceName: "Touch-up" },
      { serviceName: "Tattoo Aftercare" },
      { serviceName: "Piercing" },
      { serviceName: "Body Art" },
      { serviceName: "Tattoo Design" },
      { serviceName: "Cosmetic Tattoo" },
    ],
  },
  {
    businessType: "Hair Removal",
    services: [
      { serviceName: "Waxing" },
      { serviceName: "Laser Hair Removal" },
      { serviceName: "Threading" },
      { serviceName: "Sugaring" },
      { serviceName: "Electrolysis" },
      { serviceName: "Eyebrow Shaping" },
      { serviceName: "Bikini Wax" },
      { serviceName: "Brazilian Wax" },
      { serviceName: "Underarm Wax" },
      { serviceName: "Leg Wax" },
    ],
  },
  {
    businessType: "Piercing",
    services: [
      { serviceName: "Ear Piercing" },
      { serviceName: "Nose Piercing" },
      { serviceName: "Belly Button Piercing" },
      { serviceName: "Tongue Piercing" },
      { serviceName: "Lip Piercing" },
      { serviceName: "Eyebrow Piercing" },
      { serviceName: "Nipple Piercing" },
      { serviceName: "Septum Piercing" },
      { serviceName: "Surface Piercing" },
      { serviceName: "Piercing Removal" },
    ],
  },
  {
    businessType: "Pet Services",
    services: [
      { serviceName: "Grooming" },
      { serviceName: "Bathing" },
      { serviceName: "Nail Trimming" },
      { serviceName: "Ear Cleaning" },
      { serviceName: "Teeth Cleaning" },
      { serviceName: "Fur Trimming" },
      { serviceName: "De-shedding" },
      { serviceName: "Flea Treatment" },
      { serviceName: "Pet Sitting" },
      { serviceName: "Dog Walking" },
    ],
  },
];

module.exports = typeAndServicesSeedData;
